image: ros:noetic

before_script:
  - apt-get update && apt-get install -y python-rosdep python-rosinstall python-vcstool
  - rosdep update
  - mkdir -p ~/catkin_ws/src
  - cd ~/catkin_ws
  - catkin_init_workspace src
  - cd src
  - git clone https://github.com/yourusername/yourrepository.git
  - cd ..
  - rosdep install --from-paths src --ignore-src -r -y
  - catkin_make

test:
  script:
    - source devel/setup.bash
    - timeout --signal=SIGINT 1m roslaunch yourpackage yourlaunchfile.launch