image: ros:noetic

before_script:
  #- apt-get update && apt-get install -y python-rosdep python-rosinstall python-vcstool
  #- rosdep update
  - mkdir -p ~/catkin_ws/src
  - cd ~/catkin_ws
  - cd src
  - git clone https://gitlab.kuleuven.be/robotgenskill/ros-packages/invariants_py_ros
  - cd ..
  - catkin_make -DPYTHON_EXECUTABLE=/usr/bin/python3

test:
  script:
    - source devel/setup.bash
    - rospack profile
    - timeout --signal=SIGINT 1m roslaunch invariants_py_ros launch_invars_calc_test.launch
