image: osrf/ros:noetic-desktop-full

before_script:
  - apt-get update && apt-get install -y git
  #- rosdep update
  - which ros
  - source /opt/ros/noetic/setup.bash
  - mkdir -p ~/catkin_ws/src
  - cd ~/catkin_ws
  - cd src
  - git clone https://gitlab.kuleuven.be/robotgenskill/ros-packages/invariants_py_ros
  - cd ..
  - catkin build

test:
  script:
    - source devel/setup.bash
    - rospack profile
    - timeout --signal=SIGINT 1m roslaunch invariants_py_ros launch_invars_calc_test.launch
